# Generated by Django 4.0.5 on 2022-11-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0005_remove_csv_file_upload_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_file_upload',
            name='csv_file',
            field=models.FileField(upload_to='static/datasets/', verbose_name='XVdataset'),
        ),
    ]
